sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create an image with dockerfile"
  - docker build -t leesm2075/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true leesm2075/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"
